### ISSUE TITLE
V3 Deprecation Warning - July 2023

### ISSUE THREAD

**Issue by SBurwash** [MeltanoLabs/tap-google-analytics#43]
Good day,

There is a deprecation warning for google analytics V3 planned for july 2023: [Introducing Google Analytics 4 (GA4) - Analytics Help](https://support.google.com/analytics/answer/10089681)

I was wondering if the current tap was already using GA4 instead of GA3.

**Comment by pnadolny13** [comment]
@SBurwash thanks for opening this!

This is what I found:

- This tap currently uses the reporting API v4 https://developers.google.com/analytics/devguides/reporting/core/v4 which has a note in its docs saying it doesnt support GA4 properties
<img width="921" alt="Screen Shot 2022-07-06 at 9 11 02 AM" src="https://user-images.githubusercontent.com/27376735/177558086-ab72fbe8-abde-4364-a4f3-67ffe495316b.png">

-  It refers you to use the new GA4 "Analytics Data API" for that https://developers.google.com/analytics/devguides/reporting/data/v1
- The GA4 API is currently alpha/beta but looks like it has similar functionality
- We might be able to use [runReport](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport) similar to how we use [analytics.reports()](https://github.com/MeltanoLabs/tap-google-analytics/blob/main/tap_google_analytics/client.py#L322) right now. The dimensions/metrics/etc filters look similar at first glance
- The schemas might have changed https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema
- Theres a new python client that looks like its also still beta https://github.com/googleapis/python-analytics-data


We update the current tap to support the new API, probably supporting both APIs but can be toggled using a config setting. Eventually deprecating the legacy API functionality once its deprecated. We're already using releases in this repo so we can bump to v.1.0.0 which lets users continue to use the legacy functionality and upgrade when theyre ready.

**Comment by SBurwash** [comment]
I have a fairly busy week, but I'll try giving it a poke when I can :D

**Comment by astrojuanlu** [comment]
+1 for this tap to support GA4, in our case we have already migrated all our properties.

> Data is not synced from existing Universal Analytics instances when migrating to Google Analytics 4 and thus every day without your Google Analytics 4 property is a day of “data lost”.

([Source](https://wearekemb.com/en/how-to-migrate-to-google-analytics-4-and-why-you-should-do-it-now/))

**Comment by pnadolny13** [comment]
We're moving off google analytics so in the next couple months I won't personally be using this tap in production anymore but I know a ton of people do and I'm happy to help get it migrated. It's just lower priority on my list of things I need to do so wanted to be transparent.

If anyone else is using this in production and has time to contribute and get it upgraded, let me know, it would be greatly appreciated by me (and the community)! 😄

**Comment by pnadolny13** [comment]
Theres a singer GA4 tap https://github.com/singer-io/tap-ga4.

**Comment by fakhavan** [comment]
Hi everyone!

I wanted to share my experience using [this singer tap](https://github.com/connorflyn/tap-google-analytics-v4) that I discovered in the Meltano Slack channel. With a few minor edits, I was able to successfully run an ELT pipeline from GA4 using this tap.

I thought this can be helpful to anyone else who may be interested in updating the official Meltano tap.

Cheers

**Comment by edgarrmondragon** [comment]
Hey @fakhavan, that's great! Would you be willing to work on a PR with your edits?

**Comment by pnadolny13** [comment]
This was completed by https://github.com/MeltanoLabs/tap-google-analytics/pull/142
